# Generated by Django 5.0.14 on 2026-05-02 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('search_enabled', models.BooleanField(default=True)),
                ('booking_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_searchable', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('HEALTHY', 'Healthy'), ('FAILING', 'Failing'), ('RECOVERING', 'Recovering'), ('DISABLED', 'Disabled')], db_index=True, default='HEALTHY', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('avg_response_ms', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('is_healthy', models.BooleanField(db_index=True, default=True)),
                ('airline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='airlines.airline')),
            ],
            options={
                'verbose_name': 'Provider Health',
                'verbose_name_plural': 'Provider Health',
                'ordering': ['airline__priority', 'airline__name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_duration_mins', models.PositiveIntegerField(blank=True, help_text='Optional route duration estimate', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='airlines.airline')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='airlines.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='airlines.airport')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['airline__priority', 'from_airport__city'],
                'indexes': [models.Index(fields=['airline', 'from_airport', 'to_airport'], name='airlines_ro_airline_b6559c_idx'), models.Index(fields=['from_airport', 'to_airport'], name='airlines_ro_from_ai_9b23a6_idx'), models.Index(fields=['is_active'], name='airlines_ro_is_acti_45bd0e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(check=models.Q(('from_airport', models.F('to_airport')), _negated=True), name='prevent_same_origin_destination'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('airline', 'from_airport', 'to_airport')},
        ),
    ]
